# Site settings
title: ME414 - EstatÃ­stica para Experimentalistas
email: samara@ime.unicamp.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  samarafk
github_username:  benilton
# Build settings
markdown: kramdown
